# Project 1a
1.	Import an XML file using python
2.	Import a JSON file and analyze how different parts of JSON file can be parsed according to the business use case
3.	Import the breast cancer dataset from sklearn library and attach the target variable data to the features data and store it in a JSON file
4.	Make a regression dataset (500) with 7 features while having 4 informative features and store them on disk in a csv file

## 1. Import an XML file using python

In [13]:
# importing element tree
import xml.etree.ElementTree as ET 

# Pass the path of the xml document 


tree = ET.parse("movies.xml")

In [14]:
# get the parent tag 
root = tree.getroot()

In [15]:
# print the root (parent) tag along with its memory location 
print(root)

<Element 'collection' at 0x00000184A5409220>

In [16]:
# print the attributes of the first tag  
print(root[0].attrib)

{'title': 'Enemy Behind'}

In [17]:
#print all the attributes of the tags
for i in root:
  print(i.attrib)

{'title': 'Enemy Behind'}
{'title': 'Transformers'}
{'title': 'Trigun'}
{'title': 'Ishtar'}

In [18]:
#printing the details of each tag
for i in root:
  print(i.attrib)
  for j in i:
    print("\t",j.tag,":",j.text)

{'title': 'Enemy Behind'}
	 type : War, Thriller
	 format : DVD
	 year : 2003
	 rating : PG
	 stars : 10
	 description : Talk about a US-Japan war
{'title': 'Transformers'}
	 type : Anime, Science Fiction
	 format : DVD
	 year : 1989
	 rating : R
	 stars : 8
	 description : A schientific fiction
{'title': 'Trigun'}
	 type : Anime, Action
	 format : DVD
	 episodes : 4
	 rating : PG
	 stars : 10
	 description : Vash the Stampede!
{'title': 'Ishtar'}
	 type : Comedy
	 format : VHS
	 rating : PG
	 stars : 2
	 description : Viewable boredom

## 2. Import a JSON file and analyze how different parts of JSON file can be parsed according to the business use case

In [19]:
#importing json to work on json files
import json

#opening a json file
f = open("Sample.json")

In [20]:
print(f)

<_io.TextIOWrapper name='Sample.json' mode='r' encoding='cp1252'>

In [21]:
#getting contents of json file as a dictionary
data = json.load(f)

print(data)

{'firstName': 'Jane', 'lastName': 'Doe', 'hobbies': ['running', 'sky diving', 'singing'], 'age': 35, 'children': [{'firstName': 'Alice', 'age': 6}, {'firstName': 'Bob', 'age': 8}]}

In [24]:

# Iterating through the json list
for i in data['hobbies']:
    print((i))

running
sky diving
singing

In [25]:
print(data.keys())

dict_keys(['firstName', 'lastName', 'hobbies', 'age', 'children'])

## 3. Import the breast cancer dataset from sklearn library and attach the target variable data to the features data and store it in a JSON file

In [31]:
import pandas as pd

#importing the Sklearn Dataset breast_cancer
from sklearn.datasets import load_breast_cancer

#importing data
data = load_breast_cancer()

#getting the list of features and target in the dataset
print("The Features in the dataset are : \n",data.feature_names)
print("The Target is : \n",data.target_names)

The Features in the dataset are :
 ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
The Target is :
 ['malignant' 'benign']

In [32]:
#creating a pandas dataframe from the data
df = pd.DataFrame(data = data.data, columns = data.feature_names)
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [33]:
#the above dataset doesnot contain the target values from the actual dataset
#now Attaching the target to the New data_frame
df['Target'] = data.target
#grttinh the overall view of New_df
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

In [35]:
#Exporting the Data_set so obtained in a JSON file
df.to_json("Breast_cancer_dataset.json")

## 4. Make a regression dataset (500) with 7 features while having 4 informative features and store them on disk in a csv file

In [47]:
#We are naming our dataset as Sample_Df
#creating 7 features
Features = ['F1','F2','F3','F4','F5','F6','F7']

from sklearn import datasets

#creating a random dataset
Sample_x,Sample_y = datasets.make_regression(n_samples=500,n_features=7,n_informative=4,random_state=2)

#creating a pandas dataframe  
Sample_Df = pd.DataFrame(data = Sample_x,columns = Features)

#attaching the target values to the dataset
Sample_Df['Target'] = Sample_y

In [48]:
#printing top 5 headers
Sample_Df.head()

,F1,F2,F3,F4,F5,F6,F7,Target
0,-0.432227,0.300534,-0.911725,1.170568,0.865162,-0.287105,-0.328203,53.330191
1,-1.610499,0.789060,0.499940,-0.631119,-0.834515,0.819885,-1.621674,-35.453782
2,1.552335,-0.931714,0.471300,0.642954,-0.794150,0.241037,0.326331,82.000581
3,1.942956,0.208003,-1.706041,1.546339,1.055692,-0.812017,0.214760,55.995738
4,-2.404226,-1.001305,-0.507074,1.301120,-0.258049,-1.637614,0.099499,-41.448585

In [49]:
#saving the data into csv format
Sample_Df.to_csv("Regression_Dataset.csv")